import argparse
from importlib import util
from pathlib import Path

from core.factory import StrategyFactory


def analyze(config_module):
    strategy = StrategyFactory.create(config_module.TradingConfig())
    strategy.calculate()
    strategy.display_results()


def _load_config_module(config_path: str):
    path = Path(config_path).resolve()
    spec = util.spec_from_file_location(f"cfg_{path.stem}", path)
    if not spec or not spec.loader:
        raise ValueError(f"Unable to load config module from: {path}")
    module = util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main() -> int:
    parser = argparse.ArgumentParser(description="Run stock analysis")
    parser.add_argument("--config", help="Path to stock config file generated by chart_program")
    args = parser.parse_args()

    if args.config:
        analyze(_load_config_module(args.config))
        return 0

    from configs.stocks import BFT

    analyze(BFT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
